name: CI-Weekly

on:
  schedule:
    - cron: '0 1 * * 1' # test every Monday at 1AM

  workflow_dispatch:

jobs:
  spack-job: 
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test Spack Install
          run:  ./spack.sh

